with-expecter: True
inpackage: false
dir: "{{ .InterfaceDir }}/../mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/lyn0904/eebus-go/api:
  github.com/lyn0904/eebus-go/usecases/api:
